[build-system]
requires = ["setuptools>=69.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-playground-backend"
version = "1.0.0"
description = "AI Playground Backend"
requires-python = ">=3.11,<3.12"

[tool.setuptools]
packages = ["server"]
